# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeA_cpp <- function(Pedigree) {
    .Call(`_blupADC_makeA_cpp`, Pedigree)
}

G_matrix_cpp <- function(M, base = FALSE, trace = FALSE, metafounder = FALSE, inverse = FALSE) {
    .Call(`_blupADC_G_matrix_cpp`, M, base, trace, metafounder, inverse)
}

Deviation_matrix_cpp <- function(M, inverse = FALSE, base = FALSE, trace = FALSE) {
    .Call(`_blupADC_Deviation_matrix_cpp`, M, inverse, base, trace)
}

Dominance_matrix_cpp <- function(M, inverse = TRUE, base = FALSE, trace = FALSE) {
    .Call(`_blupADC_Dominance_matrix_cpp`, M, inverse, base, trace)
}

APY_cpp <- function(G, IND_Proven, IND_G) {
    .Call(`_blupADC_APY_cpp`, G, IND_Proven, IND_G)
}

APY_inverse_cpp <- function(M, IND_geno, APY_eigen_threshold = 0.95, APY_n_core = 0L, re_inverse = FALSE) {
    .Call(`_blupADC_APY_inverse_cpp`, M, IND_geno, APY_eigen_threshold, APY_n_core, re_inverse)
}

makeAinv_cpp <- function(Pedigree, inbreeding = FALSE) {
    .Call(`_blupADC_makeAinv_cpp`, Pedigree, inbreeding)
}

cal_homo_inbred_cpp <- function(data_genumeric, IND_geno) {
    .Call(`_blupADC_cal_homo_inbred_cpp`, data_genumeric, IND_geno)
}

makeInbreeding_cpp <- function(Pedigree) {
    .Call(`_blupADC_makeInbreeding_cpp`, Pedigree)
}

makeD_cpp <- function(Pedigree, inverse = FALSE) {
    .Call(`_blupADC_makeD_cpp`, Pedigree, inverse)
}

gene_dropping_D <- function(Pedigree, inverse = FALSE, iteration = 1000L, diagnoal = TRUE, cpu_cores = 1L) {
    .Call(`_blupADC_gene_dropping_D`, Pedigree, inverse, iteration, diagnoal, cpu_cores)
}

makeHA_cpp <- function(Pedigree, M, IND_geno, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, APY_algorithm = FALSE, APY_eigen_threshold = 0.95, APY_n_core = 0L, direct = FALSE, inverse = TRUE, omega = 0.05) {
    .Call(`_blupADC_makeHA_cpp`, Pedigree, M, IND_geno, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, APY_algorithm, APY_eigen_threshold, APY_n_core, direct, inverse, omega)
}

makeHA_metafounder_cpp <- function(Pedigree, M, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, direct = FALSE, inverse = TRUE, omega = 0.05) {
    .Call(`_blupADC_makeHA_metafounder_cpp`, Pedigree, M, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, direct, inverse, omega)
}

bigmemory_double_type <- function(pBigMat, numeric_file_name, numeric_file_path, cpu_cores = 1L) {
    .Call(`_blupADC_bigmemory_double_type`, pBigMat, numeric_file_name, numeric_file_path, cpu_cores)
}

bigmemory_object_convert <- function(input_data_numeric, bigmemory_data_name, bigmemory_data_path) {
    .Call(`_blupADC_bigmemory_object_convert`, input_data_numeric, bigmemory_data_name, bigmemory_data_path)
}

makeA_tmp_cpp <- function(Pedigree) {
    .Call(`_blupADC_makeA_tmp_cpp`, Pedigree)
}

G_matrix_memory_cpp <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, base = FALSE, trace = FALSE, metafounder = FALSE, inverse = FALSE) {
    .Call(`_blupADC_G_matrix_memory_cpp`, pBigMat, bigmemory_data_name, bigmemory_data_path, base, trace, metafounder, inverse)
}

Deviation_matrix_memory_cpp <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, base = FALSE, trace = FALSE, inverse = FALSE) {
    .Call(`_blupADC_Deviation_matrix_memory_cpp`, pBigMat, bigmemory_data_name, bigmemory_data_path, base, trace, inverse)
}

Dominance_matrix_memory_cpp <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, base = FALSE, trace = FALSE, inverse = FALSE) {
    .Call(`_blupADC_Dominance_matrix_memory_cpp`, pBigMat, bigmemory_data_name, bigmemory_data_path, base, trace, inverse)
}

APY_memory_cpp <- function(pBigMat_G, pBigMat_Ginv, IND_Proven, IND_G) {
    invisible(.Call(`_blupADC_APY_memory_cpp`, pBigMat_G, pBigMat_Ginv, IND_Proven, IND_G))
}

APY_inverse_memory_cpp <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, APY_eigen_threshold = 0.95, APY_n_core = 0L, re_inverse = FALSE) {
    .Call(`_blupADC_APY_inverse_memory_cpp`, pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, APY_eigen_threshold, APY_n_core, re_inverse)
}

makeA_memory_cpp <- function(Pedigree, bigmemory_data_name, bigmemory_data_path) {
    .Call(`_blupADC_makeA_memory_cpp`, Pedigree, bigmemory_data_name, bigmemory_data_path)
}

makeAinv_memory_cpp <- function(Pedigree, bigmemory_data_name, bigmemory_data_path, inbreeding = FALSE) {
    .Call(`_blupADC_makeAinv_memory_cpp`, Pedigree, bigmemory_data_name, bigmemory_data_path, inbreeding)
}

cal_homo_inbred_memory_cpp <- function(pBigMat, IND_geno) {
    .Call(`_blupADC_cal_homo_inbred_memory_cpp`, pBigMat, IND_geno)
}

makeInbreeding_memory_cpp <- function(Pedigree) {
    .Call(`_blupADC_makeInbreeding_memory_cpp`, Pedigree)
}

makeD_memory_cpp <- function(Pedigree, bigmemory_data_name, bigmemory_data_path, inverse = FALSE) {
    .Call(`_blupADC_makeD_memory_cpp`, Pedigree, bigmemory_data_name, bigmemory_data_path, inverse)
}

gene_dropping_memory_D <- function(Pedigree, bigmemory_data_name, bigmemory_data_path, inverse = FALSE, iteration = 1000L, diagnoal = TRUE, cpu_cores = 1L) {
    .Call(`_blupADC_gene_dropping_memory_D`, Pedigree, bigmemory_data_name, bigmemory_data_path, inverse, iteration, diagnoal, cpu_cores)
}

makeHA_memory_cpp <- function(Pedigree, pBigMat, IND_geno, bigmemory_data_name, bigmemory_data_path, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, APY_algorithm = FALSE, APY_eigen_threshold = 0.95, APY_n_core = 0L, direct = FALSE, inverse = TRUE, omega = 0.05) {
    .Call(`_blupADC_makeHA_memory_cpp`, Pedigree, pBigMat, IND_geno, bigmemory_data_name, bigmemory_data_path, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, APY_algorithm, APY_eigen_threshold, APY_n_core, direct, inverse, omega)
}

makeHA_metafounder_memory_cpp <- function(Pedigree, pBigMat, IND_geno, bigmemory_data_name, bigmemory_data_path, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, direct = FALSE, inverse = TRUE, omega = 0.05) {
    .Call(`_blupADC_makeHA_metafounder_memory_cpp`, Pedigree, pBigMat, IND_geno, bigmemory_data_name, bigmemory_data_path, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, direct, inverse, omega)
}

K_matrix_cal_memory <- function(numeric_address, bigmemory_data_name, bigmemory_data_path, IND_geno, Pedigree, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, H_A_direct = FALSE, omega = 0.05, base = FALSE, trace = FALSE, metafounder = FALSE, inverse = FALSE, gene_dropping_iteration = 1000L, type = 1L, cpu_cores = 1L, APY_algorithm = FALSE, APY_eigen_threshold = 0.95, APY_n_core = 0L, re_inverse = FALSE) {
    .Call(`_blupADC_K_matrix_cal_memory`, numeric_address, bigmemory_data_name, bigmemory_data_path, IND_geno, Pedigree, pos_A11, pos_A22, pos_geno, pos_A, pos_H22, H_A_direct, omega, base, trace, metafounder, inverse, gene_dropping_iteration, type, cpu_cores, APY_algorithm, APY_eigen_threshold, APY_n_core, re_inverse)
}

judge_character_string <- function(left, b) {
    .Call(`_blupADC_judge_character_string`, left, b)
}

full_generation_conversion <- function(generation_names, ped) {
    .Call(`_blupADC_full_generation_conversion`, generation_names, ped)
}

numeric_overlap_cpp <- function(numeric, overlap_threshold = 0.9, cpu_cores = 1L, dis_progress = TRUE) {
    .Call(`_blupADC_numeric_overlap_cpp`, numeric, overlap_threshold, cpu_cores, dis_progress)
}

get_rest_id <- function(ref, ref_index, phe, column_n, group_column, id_column) {
    .Call(`_blupADC_get_rest_id`, ref, ref_index, phe, column_n, group_column, id_column)
}

phased_haplotype_to_numeric_cpp <- function(block_start, block_end, data_hap, haplotype_allele, cpu_cores = 1L) {
    .Call(`_blupADC_phased_haplotype_to_numeric_cpp`, block_start, block_end, data_hap, haplotype_allele, cpu_cores)
}

phased_haplotype_to_blupf90_cpp <- function(block_start, block_end, data_hap, IND_name, haplotype_allele, cpu_cores = 1L) {
    .Call(`_blupADC_phased_haplotype_to_blupf90_cpp`, block_start, block_end, data_hap, IND_name, haplotype_allele, cpu_cores)
}

unphased_haplotype_to_numeric_cpp <- function(data_hap, cpu_cores = 1L) {
    .Call(`_blupADC_unphased_haplotype_to_numeric_cpp`, data_hap, cpu_cores)
}

unphased_haplotype_to_blupf90_cpp <- function(data_hap, IND_name, cpu_cores = 1L) {
    .Call(`_blupADC_unphased_haplotype_to_blupf90_cpp`, data_hap, IND_name, cpu_cores)
}

haplotype_convertion <- function(data_hap, block_start, block_end, IND_name, type = 1L, cpu_cores = 1L) {
    .Call(`_blupADC_haplotype_convertion`, data_hap, block_start, block_end, IND_name, type, cpu_cores)
}

phased_haplotype_to_numeric_memory_cpp <- function(pBigMat_hap, pBigMat_list, numeric_file_name, numeric_file_path, block_start, block_end, cpu_cores = 1L) {
    .Call(`_blupADC_phased_haplotype_to_numeric_memory_cpp`, pBigMat_hap, pBigMat_list, numeric_file_name, numeric_file_path, block_start, block_end, cpu_cores)
}

unphased_haplotype_to_numeric_memory_cpp <- function(pBigMat_hap, pBigMat_num, cpu_cores = 1L, miss_base = ".", miss_base_num = 0L) {
    invisible(.Call(`_blupADC_unphased_haplotype_to_numeric_memory_cpp`, pBigMat_hap, pBigMat_num, cpu_cores, miss_base, miss_base_num))
}

phased_haplotype_to_blupf90_memory_cpp <- function(block_start, block_end, pBigMat_hap, pBigMat_list, IND_name, cpu_cores = 1L) {
    .Call(`_blupADC_phased_haplotype_to_blupf90_memory_cpp`, block_start, block_end, pBigMat_hap, pBigMat_list, IND_name, cpu_cores)
}

unphased_haplotype_to_blupf90_memory_cpp <- function(pBigMat_hap, IND_name, cpu_cores = 1L) {
    .Call(`_blupADC_unphased_haplotype_to_blupf90_memory_cpp`, pBigMat_hap, IND_name, cpu_cores)
}

hapmap_to_ped_cpp <- function(data_hmp, cpu_cores = 5L) {
    .Call(`_blupADC_hapmap_to_ped_cpp`, data_hmp, cpu_cores)
}

hapmap_to_numeric_cpp <- function(data_hmp, miss_base = "N", miss_base_num = 0L, cpu_cores = 1L) {
    .Call(`_blupADC_hapmap_to_numeric_cpp`, data_hmp, miss_base, miss_base_num, cpu_cores)
}

get_blupf90_allele_string_hapmap <- function(allele_string_col, Ref_type, miss_base, miss_base_num, max_length) {
    .Call(`_blupADC_get_blupf90_allele_string_hapmap`, allele_string_col, Ref_type, miss_base, miss_base_num, max_length)
}

hapmap_to_blupf90_cpp <- function(data_hmp, miss_base = "N", miss_base_num = 0L, cpu_cores = 1L) {
    .Call(`_blupADC_hapmap_to_blupf90_cpp`, data_hmp, miss_base, miss_base_num, cpu_cores)
}

hapmap_to_VCF_cpp <- function(data_hmp, cpu_cores = 1L, miss_base = "N", phased_symbol = "/") {
    .Call(`_blupADC_hapmap_to_VCF_cpp`, data_hmp, cpu_cores, miss_base, phased_symbol)
}

hapmap_to_VCF_cpp1 <- function(data_hmp, cpu_cores = 1L, miss_base = ".", phased_symbol = "/") {
    .Call(`_blupADC_hapmap_to_VCF_cpp1`, data_hmp, cpu_cores, miss_base, phased_symbol)
}

hapmap_convertion <- function(data_hmp, type = 1L, miss_base = "N", phased_symbol = "/", miss_base_num = 5L, cpu_cores = 1L) {
    .Call(`_blupADC_hapmap_convertion`, data_hmp, type, miss_base, phased_symbol, miss_base_num, cpu_cores)
}

hapmap_to_numeric_memory_cpp <- function(data_hmp, pBigMat_num, miss_base = "N", miss_base_num = 0L, cpu_cores = 1L, type = "short") {
    invisible(.Call(`_blupADC_hapmap_to_numeric_memory_cpp`, data_hmp, pBigMat_num, miss_base, miss_base_num, cpu_cores, type))
}

plink_to_numeric_memory_cpp <- function(data_ped, data_map, pBigMat_num, cpu_cores = 5L, miss_base = "0", miss_base_num = 0L, type = "short") {
    invisible(.Call(`_blupADC_plink_to_numeric_memory_cpp`, data_ped, data_map, pBigMat_num, cpu_cores, miss_base, miss_base_num, type))
}

blupf90_to_numeric_memory_cpp <- function(data_blupf90, pBigMat_num, cpu_cores = 1L, type = "short") {
    invisible(.Call(`_blupADC_blupf90_to_numeric_memory_cpp`, data_blupf90, pBigMat_num, cpu_cores, type))
}

numeric_to_blupf90_cpp <- function(data_numeric, IND_name, cpu_cores = 1L) {
    .Call(`_blupADC_numeric_to_blupf90_cpp`, data_numeric, IND_name, cpu_cores)
}

numeric_to_hapmap_cpp <- function(IND_name, data_numeric_map, data_numeric, cpu_cores = 1L, miss_base = "N") {
    .Call(`_blupADC_numeric_to_hapmap_cpp`, IND_name, data_numeric_map, data_numeric, cpu_cores, miss_base)
}

numeric_to_ped_cpp <- function(IND_name, data_numeric_map, data_numeric, cpu_cores = 1L, miss_base = "N") {
    .Call(`_blupADC_numeric_to_ped_cpp`, IND_name, data_numeric_map, data_numeric, cpu_cores, miss_base)
}

numeric_to_vcf_cpp <- function(IND_name, data_numeric_map, data_numeric, phased_symbol = "/", cpu_cores = 1L) {
    .Call(`_blupADC_numeric_to_vcf_cpp`, IND_name, data_numeric_map, data_numeric, phased_symbol, cpu_cores)
}

blupf90_to_numeric_cpp <- function(data_blupf90, cpu_cores = 1L) {
    .Call(`_blupADC_blupf90_to_numeric_cpp`, data_blupf90, cpu_cores)
}

blupf90_to_hapmap_cpp <- function(IND_name, data_blupf90_map, data_blupf90, cpu_cores = 1L, miss_base = "N") {
    .Call(`_blupADC_blupf90_to_hapmap_cpp`, IND_name, data_blupf90_map, data_blupf90, cpu_cores, miss_base)
}

blupf90_to_ped_cpp <- function(IND_name, data_blupf90_map, data_blupf90, cpu_cores = 1L, miss_base = "N") {
    .Call(`_blupADC_blupf90_to_ped_cpp`, IND_name, data_blupf90_map, data_blupf90, cpu_cores, miss_base)
}

blupf90_to_vcf_cpp <- function(IND_name, data_blupf90_map, data_blupf90, phased_symbol = "/", cpu_cores = 1L) {
    .Call(`_blupADC_blupf90_to_vcf_cpp`, IND_name, data_blupf90_map, data_blupf90, phased_symbol, cpu_cores)
}

ped_to_hapmap_cpp <- function(data_ped, data_map, cpu_cores = 5L) {
    .Call(`_blupADC_ped_to_hapmap_cpp`, data_ped, data_map, cpu_cores)
}

plink_to_vcf_cpp <- function(data_ped, data_map, cpu_cores = 1L, miss_base = "0", phased_symbol = "/") {
    .Call(`_blupADC_plink_to_vcf_cpp`, data_ped, data_map, cpu_cores, miss_base, phased_symbol)
}

plink_to_numeric_cpp <- function(data_ped, data_map, cpu_cores = 5L, miss_base = "0", miss_base_num = 0L) {
    .Call(`_blupADC_plink_to_numeric_cpp`, data_ped, data_map, cpu_cores, miss_base, miss_base_num)
}

get_blupf90_allele_string_plink <- function(allele_string_row, Ref_type, miss_base, miss_base_num, max_length) {
    .Call(`_blupADC_get_blupf90_allele_string_plink`, allele_string_row, Ref_type, miss_base, miss_base_num, max_length)
}

plink_to_blupf90_cpp <- function(data_ped, data_map, cpu_cores = 5L, miss_base = "0", miss_base_num = 0L) {
    .Call(`_blupADC_plink_to_blupf90_cpp`, data_ped, data_map, cpu_cores, miss_base, miss_base_num)
}

plink_convertion <- function(data_ped, data_map, type = 1L, miss_base = "N", phased_symbol = "/", miss_base_num = 5L, cpu_cores = 1L) {
    .Call(`_blupADC_plink_convertion`, data_ped, data_map, type, miss_base, phased_symbol, miss_base_num, cpu_cores)
}

cumulativeSum <- function(input, result) {
    invisible(.Call(`_blupADC_cumulativeSum`, input, result))
}

paste_vec_short <- function(data) {
    .Call(`_blupADC_paste_vec_short`, data)
}

get_haplotype_set_short <- function(data_haplotype) {
    .Call(`_blupADC_get_haplotype_set_short`, data_haplotype)
}

allele_get_haplotype_set_short <- function(data_haplotype, haplotype_allele, i_pos) {
    invisible(.Call(`_blupADC_allele_get_haplotype_set_short`, data_haplotype, haplotype_allele, i_pos))
}

define_block_window_kb_cpp <- function(block1, block2, tmp_data_map_3) {
    .Call(`_blupADC_define_block_window_kb_cpp`, block1, block2, tmp_data_map_3)
}

single_base_factor_cpp <- function(data, miss_base) {
    .Call(`_blupADC_single_base_factor_cpp`, data, miss_base)
}

pair_base_factor_cpp <- function(data, miss_base) {
    .Call(`_blupADC_pair_base_factor_cpp`, data, miss_base)
}

get_blupf90_allele_string_phased_vcf <- function(allele_string_col1, allele_string_col2, max_length, cumsum_haplo_type_num, n_snp) {
    .Call(`_blupADC_get_blupf90_allele_string_phased_vcf`, allele_string_col1, allele_string_col2, max_length, cumsum_haplo_type_num, n_snp)
}

get_blupf90_allele_string_numeric <- function(allele_string_row, max_length) {
    .Call(`_blupADC_get_blupf90_allele_string_numeric`, allele_string_row, max_length)
}

make_bigmemory_object_cpp <- function(nrow, ncol, file_name, file_path, type) {
    .Call(`_blupADC_make_bigmemory_object_cpp`, nrow, ncol, file_name, file_path, type)
}

make_bigmemory_object_address_cpp <- function(nrow, ncol, file_name, file_path, type) {
    .Call(`_blupADC_make_bigmemory_object_address_cpp`, nrow, ncol, file_name, file_path, type)
}

NumericMatrix_to_arma <- function(data_numeric) {
    .Call(`_blupADC_NumericMatrix_to_arma`, data_numeric)
}

DataFrame_to_arma <- function(data_numeric) {
    .Call(`_blupADC_DataFrame_to_arma`, data_numeric)
}

get_offspring_generation_cpp <- function(ped, IND_base) {
    .Call(`_blupADC_get_offspring_generation_cpp`, ped, IND_base)
}

single_pedigree_cpp <- function(ped) {
    .Call(`_blupADC_single_pedigree_cpp`, ped)
}

get_blupf90_allele_string_unphased_haplotype <- function(allele_string_col1, allele_string_col2, max_length) {
    .Call(`_blupADC_get_blupf90_allele_string_unphased_haplotype`, allele_string_col1, allele_string_col2, max_length)
}

union_cpp <- function(X, Y) {
    .Call(`_blupADC_union_cpp`, X, Y)
}

delete_bigmemory_file_cpp <- function(matrix_type, bigmemory_data_name, bigmemory_data_path, message) {
    invisible(.Call(`_blupADC_delete_bigmemory_file_cpp`, matrix_type, bigmemory_data_name, bigmemory_data_path, message))
}

get_allele <- function(Pedigree) {
    .Call(`_blupADC_get_allele`, Pedigree)
}

matrix_col3 <- function(G, IND_geno, det, cpu_cores, threshold) {
    .Call(`_blupADC_matrix_col3`, G, IND_geno, det, cpu_cores, threshold)
}

matrix_col3_memory <- function(pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold) {
    invisible(.Call(`_blupADC_matrix_col3_memory`, pBigMat, bigmemory_data_name, bigmemory_data_path, IND_geno, det, cpu_cores, threshold))
}

phased_vcf_to_haplotype_cpp <- function(data_vcf, cpu_cores = 1L) {
    .Call(`_blupADC_phased_vcf_to_haplotype_cpp`, data_vcf, cpu_cores)
}

phased_vcf_to_numeric_cpp <- function(block_start, block_end, data_vcf, haplotype_allele, cpu_cores = 1L) {
    .Call(`_blupADC_phased_vcf_to_numeric_cpp`, block_start, block_end, data_vcf, haplotype_allele, cpu_cores)
}

phased_vcf_to_blupf90_cpp <- function(block_start, block_end, data_vcf, haplotype_allele, cpu_cores = 1L) {
    .Call(`_blupADC_phased_vcf_to_blupf90_cpp`, block_start, block_end, data_vcf, haplotype_allele, cpu_cores)
}

phased_vcf_to_Plink_cpp <- function(block_start, block_end, data_vcf, haplotype_allele, cpu_cores = 1L) {
    .Call(`_blupADC_phased_vcf_to_Plink_cpp`, block_start, block_end, data_vcf, haplotype_allele, cpu_cores)
}

vcf_to_plink_cpp <- function(data_vcf, cpu_cores = 1L) {
    .Call(`_blupADC_vcf_to_plink_cpp`, data_vcf, cpu_cores)
}

vcf_to_hapmap_cpp <- function(data_vcf, cpu_cores = 1L, miss_base = "0") {
    .Call(`_blupADC_vcf_to_hapmap_cpp`, data_vcf, cpu_cores, miss_base)
}

unphased_vcf_to_numeric_cpp <- function(data_vcf, cpu_cores = 1L, miss_base = ".", miss_base_num = 0L) {
    .Call(`_blupADC_unphased_vcf_to_numeric_cpp`, data_vcf, cpu_cores, miss_base, miss_base_num)
}

unphased_vcf_to_blupf90_unopenMP <- function(data_vcf, cpu_cores = 1L, miss_base = "5", miss_base_num = 5L) {
    .Call(`_blupADC_unphased_vcf_to_blupf90_unopenMP`, data_vcf, cpu_cores, miss_base, miss_base_num)
}

get_blupf90_allele_string_unphased_vcf <- function(allele_string_row, miss_base, miss_base_num, max_length) {
    .Call(`_blupADC_get_blupf90_allele_string_unphased_vcf`, allele_string_row, miss_base, miss_base_num, max_length)
}

unphased_vcf_to_blupf90_cpp <- function(data_vcf, cpu_cores = 1L, miss_base = "5", miss_base_num = 5L) {
    .Call(`_blupADC_unphased_vcf_to_blupf90_cpp`, data_vcf, cpu_cores, miss_base, miss_base_num)
}

vcf_convertion <- function(data_vcf, block_start, block_end, type = 1L, miss_base = "N", miss_base_num = 5L, cpu_cores = 1L) {
    .Call(`_blupADC_vcf_convertion`, data_vcf, block_start, block_end, type, miss_base, miss_base_num, cpu_cores)
}

phased_vcf_to_haplotype_memory_cpp <- function(data_vcf, pBigMat_hap, cpu_cores = 1L) {
    invisible(.Call(`_blupADC_phased_vcf_to_haplotype_memory_cpp`, data_vcf, pBigMat_hap, cpu_cores))
}

phased_vcf_to_numeric_memory_cpp <- function(pBigMat_hap, pBigMat_list, numeric_file_name, numeric_file_path, block_start, block_end, data_vcf, cpu_cores = 1L) {
    .Call(`_blupADC_phased_vcf_to_numeric_memory_cpp`, pBigMat_hap, pBigMat_list, numeric_file_name, numeric_file_path, block_start, block_end, data_vcf, cpu_cores)
}

unphased_vcf_to_numeric_memory_cpp <- function(pBigMat_num, data_vcf, cpu_cores = 1L, miss_base = ".", miss_base_num = 0L) {
    invisible(.Call(`_blupADC_unphased_vcf_to_numeric_memory_cpp`, pBigMat_num, data_vcf, cpu_cores, miss_base, miss_base_num))
}

phased_vcf_blupf90_memory_cpp <- function(pBigMat_hap, pBigMat_list, block_start, block_end, data_vcf, cpu_cores = 1L) {
    .Call(`_blupADC_phased_vcf_blupf90_memory_cpp`, pBigMat_hap, pBigMat_list, block_start, block_end, data_vcf, cpu_cores)
}

